### PR TITLE
sam's edits

### PR DESCRIPTION
**Pull request by boshek**
Some slight word smithing. I've also tried to lay out a vision for pkginspector as I think our role as maintainers could be helped by folks identifying needs. If we use this platform to call for that (even a little) we may solicit some interesting feedback. 

I also tried to tone down some of review language as I think we want to place pkginspector in the context of rOpenSci's review process. 

Great work though @jtr13 . We should ensure you are the lead author here.

### CODE REVIEW

**Comment by OmaymaS** [comment]
I was also thinking, do we need to mention how `pkginspector`  fits with other reviewing packages like `pkgreviewr` and `goodpractice`?

sth like what @noamross wrote [here](https://github.com/ropenscilabs/pkginspector/issues/18) in reply to Maelle?

**Comment by boshek** [comment]
@OmaymaS Yes that would be useful content to include.

**Comment by jtr13** [comment]
Agree it should be there.  Perhaps we can simply link to that discussion.

**Comment by jtr13** [comment]
Thanks @boshek -- I think we should stick with alphabetical authorship -- no lead author.

**Pull request merged**
